### ISSUE TITLE
Document record normalizations and validations

### ISSUE THREAD

**Issue by weppos** [dnsimple/dnsimple-support#1118]
We have introduced certain normalization to RR data. [Documentation was added just for TXT](https://support.dnsimple.com/articles/txt-record/#validation), however I know there are others such as IPv6 short normalization.

Please make sure they are all documented.

I suggest to have one article per documented type, rather than reusing the current generic "what's a XYZ Record" article.
```[tasklist]
### Tasks
- [x] Document AAAA normalization https://github.com/dnsimple/dnsimple-support/pull/1119
- [x] Document CAA normalization https://github.com/dnsimple/dnsimple-support/pull/1105
- [x] Document SPF normalization https://github.com/dnsimple/dnsimple-support/pull/1105
- [x] Document TXT normalization https://github.com/dnsimple/dnsimple-support/pull/1105
```

**Comment by jacegu** [comment]
Normalization of AAAA, CAA, SPF & TXT has been documented.
