### ISSUE TITLE
Reorganize SSL certificate articles

### ISSUE THREAD

**Issue by weppos** [dnsimple/dnsimple-support#217]
I'd like to reorganize the SSL certificate articles, also in preparation of the Let's Encrypt launch.

Here's a few key goals I have in my mind:
- get rid of all the various ways we referred to "getting an SSL certificate", including _purchasing_, _requesting_, _issuing_, etc in favor of a single easy naming:
  - Ordering an SSL certificate
  - Renewing an SSL certificate
  - Rekeying (or Reissuing) and SSL certificate
  
  The reason is because each of the previously mentioned names seems misleading to me:
  - requesting: you request a certificate, regardless the order type.
  - issue: same of above
  - purchase: same of above
  
  Specifically, a renewal is a new certificate, hence you still purchase, and issue it.
- Use "obtain a certificate" when we generally refer to the action of getting a certificate (either via renewal, new order, or other ways)
- Split the process of ordering/renewing a certificate depending on the CA.

---

Here's a list of changes I'd like to apply:
- [x] (work is on #219) Dismantle the current [Getting Started](https://support.dnsimple.com/articles/getting-started-ssl-certificates/) in favor of a more generic article (I outlined a suggested stub [here](https://github.com/dnsimple/dnsimple-support/commit/094df0986e9609a9c93b3db010e23c374db83363#diff-714899a9dc31f7c0ad0d62356e22e91b). The goal is to outline the essential tasks, and potentially delegate to more specific articles where appropriate:
  - _Request the certificate_ can delegate to two articles (one per CA)
  - _Validate the certificate request_ can quickly explain the purpose of the validation, and perhaps mention that depending on the CA the validaiton is different (or link to the articles). I think, again, we want to have specific information about the validation process in the specific articles
  - _Install the certificate_ can link to the specific installing article
- [x] Clearly provide 3 articles, one for each task:
  - New certificate (Ordering?)
  - Renewal
  - Reissue
  
  I had a stub [here](https://github.com/dnsimple/dnsimple-support/commit/094df0986e9609a9c93b3db010e23c374db83363#diff-67a6ba1d9cd21126e19efe0270501a14) for the New Certificate (I was calling it Requesting).
  
  The goal of these articles is to clearly explain the step-by-step process to perform the action, with appropriate screenshots. For example, the "New Certificate" for Comodo should contain the steps we have right now spread across the Getting Started article where we show how to Order > Configure > Submit.
  
  My only concern here is that the steps clearly depends on the CA. Therefore I wonder if we should have articles per-CA (e.g. https://github.com/dnsimple/dnsimple-support/commit/094df0986e9609a9c93b3db010e23c374db83363#diff-6f4265e4732a9a5d12dce1260421182a), or per tasks.
  
  We can also have one article per task/ca combination:
  - Ordering a Standard SSL certificate
  - Ordering a Let's Encrpt SSL certificate
  - Renewing a Standard SSL certificate
  - Renewing a Let's Encrpt SSL certificate
  
  and have the global pages to act as indexes providing alternate navigation.
  - Ordering an SSL certificate
  - Renewing an SSL certificate
  
  and
  - SSL certificate with Let's Encrypt
  - SSL certificate with Standard
- [x] (done in #219) Kill https://support.dnsimple.com/articles/purchasing-ssl-certificates/ that will be inglobated in the step-by-step article to Order a standard certificate.
- [x] (done in #224) Kill https://support.dnsimple.com/articles/renewing-ssl-certificate/ that will be inglobated in the step-by-step article to Renew a standard certificate.
- [x] https://support.dnsimple.com/articles/reissuing-ssl-certificate/ same as above
- [x] All the "Obtain a certificate" sections in the per-server articles, such as https://support.dnsimple.com/articles/ssl-certificate-with-apache/ should link to the new "getting started" and/or the "Ordering an SSL certificate".

**Comment by jcaudle** [comment]
I'm going to get started on this today. I expect I'll perform these changes in separate PRs, but some things might be easy to roll together.

**Comment by jcaudle** [comment]
Once I have merged both of the outstanding tickets linked to this one, I'll close this out. I'll also update the paths to match the usage of "standard" instead of "traditional" or "Comodo" once everything is merged.

**Comment by jcaudle** [comment]
This should have been closed already by #228.
