### ISSUE TITLE
Expose search function for 3rd party consumption

### ISSUE THREAD

**Issue by dallasread** [dnsimple/dnsimple-support#636]
While working on https://github.com/dnsimple/dnsimple-app/pull/13857#pullrequestreview-453156768, @OleMchls mentioned that it would be a good idea to show the same results in the support widget AND on the support site. The original intention of the aforementioned PR was to implement specific search results for certain keywords.

@kayla-broussard and [I](https://github.com/dnsimple/dnsimple-app/pull/13857#pullrequestreview-453280700) noticed... instead of `search.json`, we could expose `search.js`, which will contain a simple function that returns the articles _exactly_ how we want them (dictionary-applied and sorted). 

```js
window.DNSimpleSupport.search('keyword', function(err, data) {
  // do something with the data.articles
});
```

Upon completion, both the support site AND the support widget will be showing the same curated results in the same order.

## Tasks

- [x] Expose `window.DNSimpleSupport.search` at support.dnsimple.com https://github.com/dnsimple/dnsimple-support/pull/648
- [x] Add dictionary to `window.DNSimpleSupport.search` https://github.com/dnsimple/dnsimple-support/pull/648
- [ ] Use `window.DNSimpleSupport.search` in the support widget (@kayla-broussard has a local branch with the codez ready to go – need to merge https://github.com/dnsimple/dnsimple-support/pull/648 first)
